In [1]:
!pip install google-api-python-client

In [ ]:
!pip install python-dotenv

In [ ]:
import pandas as pd
df = pd.read_csv("data/labeled_data-1.csv")
df.head()

Unnamed: 0  class                                              tweet
0           0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1           1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2           2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3           3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4           4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [ ]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

class                                              tweet
0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [ ]:
sampled_df = df.sample(n=250, random_state=42)
sampled_list = sampled_df["tweet"].tolist()
tweets = sampled_df['tweet'].tolist()
labels = sampled_df['class'].tolist()

In [ ]:
import perspectives_helper as ph

predictions = ph.predict_batch(tweets)
predictions

your_perspectives_api_key_here


HttpError: <HttpError 400 when requesting https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1&key=your_perspectives_api_key_here returned "API key not valid. Please pass a valid API key.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'commentanalyzer.googleapis.com'}}, {'@type': 'type.googleapis.com/google.rpc.LocalizedMessage', 'locale': 'en-US', 'message': 'API key not valid. Please pass a valid API key.'}]">

In [ ]:
labels

[1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1]

In [ ]:
import numpy as np

true = np.array(labels)
pred = np.array(predictions)

accuracy = np.mean(true == pred)
print("Accuracy =", accuracy)

NameError: name 'predictions' is not defined

In [ ]:
from sklearn.metrics import confusion_matrix, f1_score

cm = confusion_matrix(true, pred)
f1_macro = f1_score(true, pred, average="macro")

print("Confusion matrix:\n", cm)
print("Macro F1 =", f1_macro)

Confusion matrix:
 [[  0  15   2]
 [  1 178  14]
 [  0   5  35]]
Macro F1 = 0.5599055675782019


In [ ]:
for cls in [0,1,2]:
    idx = np.where(true == cls)[0]
    acc = np.mean(true[idx] == pred[idx])
    print(f"Class {cls} accuracy: {acc}")


Class 0 accuracy: 0.0
Class 1 accuracy: 0.9222797927461139
Class 2 accuracy: 0.875


In [ ]:
!pip install openai anthropic nest-asyncio

In [ ]:
import gpt_helper as gh
import claude_helper as ch

## GPT-5-nano Evaluation

In [ ]:
print("Running GPT-5-nano predictions...")
gpt_predictions = gh.predict_batch(tweets, model="gpt-5-nano-2025-08-07")
print("GPT-5-nano predictions completed!")
gpt_predictions

Running GPT-5-nano predictions...
Processing tweet 1/250...
Error processing comment: Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}
Error processing comment: Error code: 400 - {'error': {'message': "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'unsupported_parameter'}}


KeyboardInterrupt: 

In [ ]:
gpt_pred = np.array(gpt_predictions)
gpt_accuracy = np.mean(true == gpt_pred)
gpt_cm = confusion_matrix(true, gpt_pred)
gpt_f1_macro = f1_score(true, gpt_pred, average="macro")

print("GPT-5-nano Results:")
print("=" * 50)
print("Accuracy =", gpt_accuracy)
print("Confusion matrix:\n", gpt_cm)
print("Macro F1 =", gpt_f1_macro)
print("\nPer-class accuracy:")
for cls in [0,1,2]:
    idx = np.where(true == cls)[0]
    acc = np.mean(true[idx] == gpt_pred[idx])
    print(f"Class {cls} accuracy: {acc:.4f}")

## Claude-Haiku Evaluation

In [ ]:
print("Running Claude-Haiku predictions...")
claude_predictions = ch.predict_batch(tweets, model="claude-haiku-4-5-20251001")
print("Claude-Haiku predictions completed!")
claude_predictions

In [ ]:
claude_pred = np.array(claude_predictions)
claude_accuracy = np.mean(true == claude_pred)
claude_cm = confusion_matrix(true, claude_pred)
claude_f1_macro = f1_score(true, claude_pred, average="macro")

print("Claude-Haiku Results:")
print("=" * 50)
print("Accuracy =", claude_accuracy)
print("Confusion matrix:\n", claude_cm)
print("Macro F1 =", claude_f1_macro)
print("\nPer-class accuracy:")
for cls in [0,1,2]:
    idx = np.where(true == cls)[0]
    acc = np.mean(true[idx] == claude_pred[idx])
    print(f"Class {cls} accuracy: {acc:.4f}")

## Comparative Analysis

In [ ]:
results_df = pd.DataFrame({
    'Model': ['Perspectives API', 'GPT-5-nano', 'Claude-Haiku'],
    'Accuracy': [accuracy, gpt_accuracy, claude_accuracy],
    'Macro F1': [f1_macro, gpt_f1_macro, claude_f1_macro],
    'Class 0 Acc': [
        np.mean(true[np.where(true == 0)[0]] == pred[np.where(true == 0)[0]]),
        np.mean(true[np.where(true == 0)[0]] == gpt_pred[np.where(true == 0)[0]]),
        np.mean(true[np.where(true == 0)[0]] == claude_pred[np.where(true == 0)[0]])
    ],
    'Class 1 Acc': [
        np.mean(true[np.where(true == 1)[0]] == pred[np.where(true == 1)[0]]),
        np.mean(true[np.where(true == 1)[0]] == gpt_pred[np.where(true == 1)[0]]),
        np.mean(true[np.where(true == 1)[0]] == claude_pred[np.where(true == 1)[0]])
    ],
    'Class 2 Acc': [
        np.mean(true[np.where(true == 2)[0]] == pred[np.where(true == 2)[0]]),
        np.mean(true[np.where(true == 2)[0]] == gpt_pred[np.where(true == 2)[0]]),
        np.mean(true[np.where(true == 2)[0]] == claude_pred[np.where(true == 2)[0]])
    ]
})

print("\nComparative Results:")
print("=" * 80)
print(results_df.to_string(index=False))