In [1]:
!pip install google-api-python-client

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 4.6 MB/s  0:00:03 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [google-api-python-client]api-python-client]


In [5]:
!pip install python-dotenv

In [11]:
import pandas as pd
df = pd.read_csv("data/labeled_data-1.csv")
df.head()

Unnamed: 0  class                                              tweet
0           0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1           1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2           2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3           3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4           4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [15]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

class                                              tweet
0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [ ]:
sampled_df = df.sample(n=250, random_state=42)
sampled_list = sampled_df["tweet"].tolist()
tweets = sampled_df['tweet'].tolist()
labels = sampled_df['class'].tolist()

['934 8616\ni got a missed call from yo bitch',
 'RT @KINGTUNCHI_: Fucking with a bad bitch you gone need some money lil homie!',
 "RT @eanahS__: @1inkkofrosess lol my credit ain't no where near good , but I know the right man for the job .. that ho nice though!",
 "RT @Maxin_Betha Wipe the cum out of them faggot RT @80sbaby4life Contact lens is wildin can't see shit",
 "Niggas cheat on they bitch and don't expect no pay back WHATSOEVER. Yall just as naive as these bitches.",
 'Mother asked what I wanted for Christmas this year. Replied with for her to not go crazy, and my sister to not be a bitch.',
 "That's real dedication. .. &#171;@arigold_88 This bitch got diarrhea and still here, shitting up the bathroom.&#187;",
 "Kiss IMO this conductor, it's 4:30 AM have some courtesy you bitch.",
 "My momma keep talking to me like bitch gtf I'm on Twitter.",
 'RT @karlos_budah: I kno this bitch a thot she wanna meet my momma now',
 'like a bitch pic is flirting nowadays',
 '@Nien_Nunb what di

In [19]:
import perspectives_helper as ph

predictions = ph.predict_batch(tweets)
predictions

[1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 1]

In [22]:
labels

[1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1]

In [23]:
import numpy as np

true = np.array(labels)
pred = np.array(predictions)

accuracy = np.mean(true == pred)
print("Accuracy =", accuracy)

Accuracy = 0.852


In [24]:
from sklearn.metrics import confusion_matrix, f1_score

cm = confusion_matrix(true, pred)
f1_macro = f1_score(true, pred, average="macro")

print("Confusion matrix:\n", cm)
print("Macro F1 =", f1_macro)

Confusion matrix:
 [[  0  15   2]
 [  1 178  14]
 [  0   5  35]]
Macro F1 = 0.5599055675782019


In [26]:
for cls in [0,1,2]:
    idx = np.where(true == cls)[0]
    acc = np.mean(true[idx] == pred[idx])
    print(f"Class {cls} accuracy: {acc}")


Class 0 accuracy: 0.0
Class 1 accuracy: 0.9222797927461139
Class 2 accuracy: 0.875
